### ISSUE TITLE
Issue with image

### ISSUE THREAD

**Issue by fraserpal** [BobMak/SpaceShooter#2]
```
(pygame_spaceshooter) Borja@MacBook-Pro-de-Borja:~/Pygames/pygame_spaceshooter/SpaceShooter$ python Main.py 
2018-06-07 20:50:14.036 python[4335:3981441] 20:50:14.036 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Traceback (most recent call last):
  File "Main.py", line 7, in <module>
    from Menus import main_menu, player_set
  File "/Users/Borja/Pygames/pygame_spaceshooter/SpaceShooter/Menus.py", line 2, in <module>
    from Assets import *
  File "/Users/Borja/Pygames/pygame_spaceshooter/SpaceShooter/Assets.py", line 34, in <module>
    blanc = pygame.image.load("assets\\blanc.png")
pygame.error: Couldn't open assets\blanc.png
```

**Comment by fraserpal** [comment]
This is the solution:
```
blanc = pygame.image.load(os.path.join("assets", "blanc.png"))
```
Should be changed in every image load.

**Comment by BobMak** [comment]
Thanks! Changed.
